### ISSUE TITLE
Add sponsors

### ISSUE THREAD

**Issue by emilyharden** [techlahoma/thunderplains-2023#1]
Heartland is Gold sponsor
36 Deg North is in-kind donation sponsor
![36 deg north landscape](https://github.com/techlahoma/thunderplains-2023/assets/72417338/61831d6e-e8e5-4e0c-97aa-07c664e676c4)
Pick which heartland works best for you
![Heartland_Logo_REV (1)](https://github.com/techlahoma/thunderplains-2023/assets/72417338/eb829e17-e550-4c5d-831d-e12a0d6f89dd)
![Heartland_Logo_PMS](https://github.com/techlahoma/thunderplains-2023/assets/72417338/2618ba61-3e3f-42b4-883c-4fd60345e4c5)
![Heartland_Logo_K](https://github.com/techlahoma/thunderplains-2023/assets/72417338/03b38706-73ee-40e3-9ddf-4b3de1563f47)

**Comment by emilyharden** [comment]
Clevyr, local sponsor

**Comment by vlucas** [comment]
@emilyharden Do you have a logo for Clevyr?

**Comment by kacollins** [comment]
Heartland is already there, so create subsections for gold vs in-kind and add 36 Deg North?

**Comment by jsonthebson** [comment]
Add Bitness Labs as a local sponsor
![Bitness Labs](https://github.com/techlahoma/thunderplains-2023/assets/23440332/88dab529-551e-4f14-95ad-5e2d792e3855)

**Comment by jsonthebson** [comment]
add of ash and fire as exclusive lunch sponsor
![Color Logo Black Text (2)](https://github.com/techlahoma/thunderplains-2023/assets/23440332/6007a63a-027e-43f4-af0b-6c3fe340abe3)

**Comment by jsonthebson** [comment]
> Heartland is already there, so create subsections for gold vs in-kind and add 36 Deg North?

Yes- i believe there may be subsections created already

**Comment by CKCarr** [comment]
Working on the sponser section.
adding subsections and style for gold, bronze, silver, local and inkind.

**Comment by vlucas** [comment]
This has been merged and is done. Open additional issues for any new sponsorships.
