### ISSUE TITLE
Unexclude .vscode directory

### ISSUE THREAD

**Issue by pythoninthegrass** [techlahoma/thunderplains-2023#12]
On [line 39](https://github.com/pythoninthegrass/thunderplains-2023/blob/main/.gitignore#L39) of the `.gitignore` file, we've excluded the `.vscode` directory.

I can see _why_ this would be the case, but honestly, it's actually really useful to include for other contributors who also use VSCode locally.

Some of the advantages are:
* reproducing the dev environment from the maintainer's workstation
* only overrides repo workspace, not general user settings
* opens the door for tailored debugging presets

Stumbled across this as I was tempted to add a `bun.lockb` and `yarn.lock` exclusion in favor of the standard `package-lock.json` file; let me know what you think about both! Happy to open a separate issue/PR for the latter if you all think it's mission creep for this particular issue.

**Comment by vlucas** [comment]
You can remove it if you like. I use `vim` personally, so it will not affect me either way :p

**Comment by pythoninthegrass** [comment]
> I use vim personally

Man of taste I see! (I do too, just on servers and for spot edits haha)

Unexcluded in #14. Added a few other items that I thought would be useful, but can split into a separate PR if you'd like.

**Comment by kacollins** [comment]
Done in #14
