### ISSUE TITLE
gold sponsor section

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2023#17]
The gold sponsor section looks a little off. Maybe we can organize it a bit different

Exclusive sponsors
-of ash and fire
-verge okc

Gold Sponsors
-Heartland

**Comment by CKCarr** [comment]
working on this.

**Comment by CKCarr** [comment]
Are there descriptive headers I should/would incorporate for the sponsers?

- Heartland
- Bitness Labs
- 36* North

**Comment by kacollins** [comment]
I can't speak for @jsonthebson, but this is my understanding:
Heartland - Gold Sponsor
Bitness Labs - Local Sponsor
36* North - In-Kind Sponsor

**Comment by kacollins** [comment]
I believe the main problem here is that there are three sponsors listed in the Gold section, when only Heartland is Gold. (Based on my understanding of the issue description) Of Ash and Fire and The Verge OKC should be in a new section above Gold that is called Exclusive Sponsors.

**Comment by vlucas** [comment]
For the purposes of sponsorship levels, all "Exclusive" sponsors are considered to be Gold sponsors. That is why they are all under the Gold heading.

**Comment by kacollins** [comment]
Does that mean this issue no longer needs to be done? Or what exactly needs to be changed? I'll be happy to take this issue if I understand the request.

**Comment by kacollins** [comment]
@jsonthebson Is this issue good to be closed?

**Comment by jsonthebson** [comment]
yes, thank you!
