### ISSUE TITLE
make an "email to my boss" link

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2023#2]
Need to convince your boss you should attend ThunderPlains? We got you covered! Just replace all the bolded spots with your info!

Subject: Request to Attend ThunderPlains Conference by Techlahoma Foundation

Dear **[Boss’s Name]**,

I am writing to seek approval to attend the upcoming ThunderPlains Developer Conference hosted by Techlahoma Foundation. I firmly believe that attending this event can bring a wealth of benefits to **[Company's Name]** and to our team. Let me outline the reasons why:

Up-to-Date Industry Knowledge: ThunderPlains is renowned for featuring talks from industry leaders and innovators. By attending, I'll have the opportunity to learn about the latest trends, tools, and best practices in web and mobile development. This knowledge can help us stay ahead of the curve and implement cutting-edge strategies in our projects.

Networking Opportunities: The conference gathers professionals from various sectors and backgrounds, offering a platform to network, discuss, and potentially collaborate. By interacting with other attendees, I could forge connections that could lead to valuable partnerships, client leads, or other opportunities for [Company's Name].

Cost-Effective Learning: While there are many online courses available, the concentrated and immersive nature of conferences allows for a more efficient and effective learning experience. Additionally, attending ThunderPlains can be more cost-effective than enrolling in multiple courses or trainings.

Team Morale and Motivation: Conferences have a way of rejuvenating passion and motivation. Being surrounded by industry leaders and peers can be inspiring. I am confident that the experience will reenergize me, and I’ll return with fresh ideas and enthusiasm to inject into our projects.

Promoting **[Company's Name]**: Being present at such events can also serve as a form of visibility for our company. We can engage in conversations that place **[Company's Name]** in a favorable light and potentially attract talent or clients.

In recognition of the operational demands while I’m away, I am committed to ensuring that all my responsibilities are covered during my absence. I will prepare a plan detailing how my tasks will be managed, ensuring no disruption to our workflow.

To review the full agenda, please go to thunderplainsconf.com.

Additionally, I would be more than happy to share the knowledge I acquire at the conference with the team. We can organize a post-conference session where I can provide an overview of the most valuable takeaways, ensuring the entire team benefits from this opportunity.

Thank you for considering this request. I genuinely believe that the insights and connections from the ThunderPlains Conference will greatly benefit our team and **[Company's Name]** as a whole. I am eager to hear your thoughts on this.

Best regards,

**[Your Name]**

**Comment by jsonthebson** [comment]
https://docs.google.com/document/d/1SOY5c8O0WOtmM4umjgPeLH0EHPywXBrVLn9tnZWmq5o/edit?usp=sharing

heres a link. Make sure to put this note with it: Need to convince your boss you should attend ThunderPlains? We got you covered! Just replace all the bolded spots with your info!

**Comment by kacollins** [comment]
Is this just adding a small section with the note and a link button going to the Google doc? Assuming it also needs to be added to the navigation at the top.

**Comment by jsonthebson** [comment]
yes and yes.

**Comment by laylark** [comment]
@jsonthebson I can take care of this one!

**Comment by vlucas** [comment]
Closed with #15
