### ISSUE TITLE
"What to Tell My Boss (PDF)" Link is Broken

### ISSUE THREAD

**Issue by kacollins** [techlahoma/thunderplains-2023#21]
href is missing for [this link](https://github.com/techlahoma/thunderplains-2023/blob/50371ae853c0662002045ff763efc91a0bf99889/app/page.tsx#L148)

**Comment by hkbertoson** [comment]
Would the PDF be the same as this? https://docs.google.com/document/d/1SOY5c8O0WOtmM4umjgPeLH0EHPywXBrVLn9tnZWmq5o/edit

**Comment by kacollins** [comment]
Yep, I believe that's it!
