### ISSUE TITLE
Add Pictures

### ISSUE THREAD

**Issue by hkbertoson** [techlahoma/thunderplains-2023#23]
It would be nice to have Pictures of the people here instead of just a blank area. 

![Screenshot 2023-10-20 at 11 38 58 AM](https://github.com/techlahoma/thunderplains-2023/assets/44106297/7ebb18a5-41d3-45e5-88c5-d7fa2925c233)

**Comment by jsonthebson** [comment]
Yes, it would be great! Here's links to photos if someone wants to do that! 
https://airtable.com/appJOPSM7LKz6Ktqq/shr0sx49JXdV0KRQl
