### ISSUE TITLE
Additional Data input

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2023#27]
at 9:30 on the empty side: Matthew Reily, "Building a Data-Driven Culture with Observability"
at 2:30 on the empty side: Ron Dagdag, "Mixed Reality for JavaScript Developers"
at 3:30 on the empty side: Andrew Coleburn "Out of the Frying Pan, Into the Fire: A new Dev's Guide to Navigating Unfamiliar Codebases"

**Comment by kacollins** [comment]
Done in #31
