### ISSUE TITLE
Convention Center Link

### ISSUE THREAD

**Issue by kacollins** [techlahoma/thunderplains-2023#28]
Under event details, linking the [name](https://github.com/techlahoma/thunderplains-2023/blob/50371ae853c0662002045ff763efc91a0bf99889/app/page.tsx#L145) of the convention center to its website would be nice.

**Comment by fjordan95** [comment]
Good evening! I can take care of this. Can you assign this to me?

**Comment by kacollins** [comment]
Done in #47
