### ISSUE TITLE
Add to calendar link

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2023#29]
If people could have an add to calendar link, that would be neat!

https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=XzZ0bG5hcXJsZTVwNmNwYjRkaG1qNHBocGVob2owdDlrY3RpNzZjYmVlbGhtOHFiaGN0a2phcjM3ZTRvNnVyamI2aGkzMm9yYTZrcmoyb2hrNjhwNzZyMXBjZGs2NmRiaDZwb2oyc3I5YzlpbWUgZW1pbHloYXJkZW5AdGVjaGxhaG9tYS5vcmc&tmsrc=emilyharden%40techlahoma.org

and 
<a target="_blank" href="https://calendar.google.com/calendar/event?action=TEMPLATE&amp;tmeid=XzZ0bG5hcXJsZTVwNmNwYjRkaG1qNHBocGVob2owdDlrY3RpNzZjYmVlbGhtOHFiaGN0a2phcjM3ZTRvNnVyamI2aGkzMm9yYTZrcmoyb2hrNjhwNzZyMXBjZGs2NmRiaDZwb2oyc3I5YzlpbWUgZW1pbHloYXJkZW5AdGVjaGxhaG9tYS5vcmc&amp;tmsrc=emilyharden%40techlahoma.org"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_en.gif"></a>

**Comment by kacollins** [comment]
@jsonthebson This event just shows "busy" - is that what you intended?

**Comment by jsonthebson** [comment]
lets skip this, i dont know how to make it better.
