### ISSUE TITLE
update schedule

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2023#3]
make schedule have the following content (Keep all visuals the same as current site, but update new info on speaker info, session titles, etc.)

https://airtable.com/appJOPSM7LKz6Ktqq/shrPOjOjF1BKzkdF5/tblQbIRc36AyHYvUi?date=undefined&mode=undefined

**Comment by somet-code** [comment]
Working on this

**Comment by vlucas** [comment]
Lightning talks should be in the same room, not spread across 2 rooms.

Also - I am not sure we want to make things like "<person name> Hold" public on the website. It is probably better to just wait for their talk title. It should not be much longer, right?

**Comment by somet-code** [comment]
I tried again with a new PR.

**Comment by kacollins** [comment]
Is this just waiting for a talk title from Rebecca?

**Comment by kacollins** [comment]
Is this done in #44? Or what else needs to be done?

**Comment by vlucas** [comment]
This is done now.
