### ISSUE TITLE
Veterans Day Holiday

### ISSUE THREAD

**Issue by kacollins** [techlahoma/thunderplains-2023#33]
I've spoken to a couple of people who didn't know whether they have November 10 off as a holiday for Veterans Day. Should something about this be included in the "Email My Boss" section? Along the lines of "check your company's holiday list so you don't look like an idiot when you email your boss" lol.

**Comment by jsonthebson** [comment]
I like that- also we are going to add a discount of 10% for veterans with code VETERAN. I'll do a social pull, but if you want to add it to the site, feel free!

**Comment by jsonthebson** [comment]
updated the google doc

**Comment by kacollins** [comment]
Love it!
