### ISSUE TITLE
Make sponsorship prospectus an updated link

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2023#4]
Make the link for "Sponsor ThunderPlains 2023" be a link that updates as the drive file is updated, aka this link. https://drive.google.com/file/d/1sXYsG1bOBLhF2yrSkM3BDmJkyYm2aa2J/view?usp=drive_link

**Comment by somet-code** [comment]
Attempting to work on this issue

**Comment by kacollins** [comment]
Done in #6
