### ISSUE TITLE
Simian Craft Sponsor

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2023#49]
Simiancraft
![simiancraft_logo](https://github.com/techlahoma/thunderplains-2023/assets/23440332/81c3d7ea-699c-4bb8-a116-80e63300af64)
https://simiancraft.com/
Exclusive Recording Sponsor

**Comment by kacollins** [comment]
Is this considered a gold-level sponsorship?

**Comment by jsonthebson** [comment]
it's silver. :)
