### ISSUE TITLE
Add Verge

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2023#5]
Add Verge OKC as exclusive after-party sponsor. in sponsor section.
![Verge_Logo__Horiz_Lockup_Bk](https://github.com/techlahoma/thunderplains-2023/assets/23440332/a9e75358-4a06-4efb-ab7d-6dfed5cd7ea8)

**Comment by pythoninthegrass** [comment]
Hi @jsonthebson! Please assign this issue to me. Working on it now.

**Comment by pythoninthegrass** [comment]
https://github.com/techlahoma/thunderplains-2023/pull/10

**Comment by vlucas** [comment]
Done.
